// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJqQTBZxgcmzO-c98bsw2reZ4GcaYFA3E',
    appId: '1:931800449137:web:60219087fae5b5e1ac9bd0',
    messagingSenderId: '931800449137',
    projectId: 'bodytherapy-3b66c',
    authDomain: 'bodytherapy-3b66c.firebaseapp.com',
    storageBucket: 'bodytherapy-3b66c.firebasestorage.app',
    measurementId: 'G-TZ4QS541G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmFLwJfkoEmEdylWhXQal05HWNpfTae0k',
    appId: '1:931800449137:android:a047a19543d74f57ac9bd0',
    messagingSenderId: '931800449137',
    projectId: 'bodytherapy-3b66c',
    storageBucket: 'bodytherapy-3b66c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc3XUNlu4iiG9Cp8FyZIpKySkI8YJwYS0',
    appId: '1:931800449137:ios:69eb99f762e934b5ac9bd0',
    messagingSenderId: '931800449137',
    projectId: 'bodytherapy-3b66c',
    storageBucket: 'bodytherapy-3b66c.firebasestorage.app',
    iosBundleId: 'com.app.bodytherapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc3XUNlu4iiG9Cp8FyZIpKySkI8YJwYS0',
    appId: '1:931800449137:ios:249308ba2f46350dac9bd0',
    messagingSenderId: '931800449137',
    projectId: 'bodytherapy-3b66c',
    storageBucket: 'bodytherapy-3b66c.firebasestorage.app',
    iosBundleId: 'com.example.bodytherapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJqQTBZxgcmzO-c98bsw2reZ4GcaYFA3E',
    appId: '1:931800449137:web:2c9fe55752a56919ac9bd0',
    messagingSenderId: '931800449137',
    projectId: 'bodytherapy-3b66c',
    authDomain: 'bodytherapy-3b66c.firebaseapp.com',
    storageBucket: 'bodytherapy-3b66c.firebasestorage.app',
    measurementId: 'G-P0NRQ6TYEY',
  );

}